#!/bin/bash

# Generate the dirs/files necessary for osg-build
mkdir upstream
[[ -z $VERSION ]] && VERSION=$(rpmspec -P "/$REPO_NAME/rpm/$REPO_NAME.spec" | awk '/^Version:/ {print $2; exit}')
[[ -z $TARBALL_NAME ]] && TARBALL_NAME="$REPO_NAME-$VERSION.tar.gz"
echo "type=git url=/$REPO_NAME name=$REPO_NAME tarball=$TARBALL_NAME tag=HEAD hash=dummy" > upstream/local.git.source

# Run osg-build
osg-build --verbose mock .

if [ $? -ne 0 ]; then
    for build_log in state.log root.log build.log; do
        echo "### $build_log ###"
        cat /u/_build_results/$build_log
    done
fi
