#!/bin/bash

# Generate the dirs/files necessary for osg-build
mkdir upstream
VERSION=$(awk '/Version:/ {print $2}' "/$REPO_NAME/rpm/$REPO_NAME.spec")
echo "type=git url=/$REPO_NAME name=$REPO_NAME tarball=$REPO_NAME-$VERSION.tar.gz tag=HEAD hash=dummy" > upstream/local.git.source

# Run osg-build
osg-build rpmbuild .
