#!/bin/bash

CONTAINER_NAME=osg-build

t=
[[ -t 0 && -t 1 ]] && t=-t

docker=docker
if command -v podman &>/dev/null; then
    docker=podman
fi

$docker exec -i $t $CONTAINER_NAME \
    /usr/local/bin/command-wrapper.sh "$(pwd -P)" osg-build "$@"
