#!/bin/bash

CONTAINER_NAME=osg-build
command=osg-koji

# only allocate a tty if stdin and stdout are both ttys.
# Allocating a tty causes piping issues (for example, the output side
# will contain CRLF line terminators instead of LF)
t=
[[ -t 0 && -t 1 ]] && t=-t

docker=docker
if command -v podman &>/dev/null; then
    docker=podman
fi

koji_hub_arg=
if [[ $KOJI_HUB ]]; then
    koji_hub_arg=--env=KOJI_HUB=$KOJI_HUB
fi

$docker exec -i $t $koji_hub_arg $CONTAINER_NAME \
    /usr/local/bin/command-wrapper.sh "$(pwd -P)" "$command" "$@"
