#!/bin/bash

CONTAINER_NAME=osgbuilder
IMAGE=matyasselmeci:osgbuilder

die () {
    echo "$@" 1>&2
    exit 1
}

[[ -r $HOME/.globus/usercert.pem ]] || die "~/.globus/usercert.pem not found or not readable"
[[ -r $HOME/.globus/userkey.pem ]] || die "~/.globus/userkey.pem not found or not readable"

work_dir=~/work

[[ -x $work_dir ]] || die "$work_dir not found or not readable"

work_dir=$(cd "$work_dir" && pwd -P) || die "error getting absolute path of $work_dir"

set -eu

hash=$(docker ps --latest --quiet --filter name=$CONTAINER_NAME)

if [[ -z $hash ]]; then
    echo -n 'creating docker container: '
    docker create -it \
                      --volume "$HOME/.globus":/u/.globus \
                      --volume "$work_dir":/u/work \
                      --name $CONTAINER_NAME \
                      $IMAGE  && \
        sleep 2
else
    echo "docker container \`$CONTAINER_NAME' already exists"
fi

docker start $CONTAINER_NAME
sleep 2

docker exec $CONTAINER_NAME \
    bash -c "echo '$work_dir' > /u/.work_dir"

