#!/bin/bash

CONTAINER_NAME=osg-build

# only allocate a tty if stdin and stdout are both ttys.
# Allocating a tty causes piping issues (for example, the output side
# will contain CRLF line terminators instead of LF)
t=
[[ -t 0 && -t 1 ]] && t=-t

docker=docker
if command -v podman &>/dev/null; then
    docker=podman
fi

$docker exec -i $t -u0 $CONTAINER_NAME \
    sh -c 'cd /usr/local/src/osg-build && git pull --autostash --rebase && make -s install && echo ok'
